"""Partition cutover for sqlery_queued_job (standalone PG existing installs).

STOP-THE-WORLD MIGRATION — operational protocol (D3):
  1. Stop all workers and daemons (they must not be writing during the rename/copy).
  2. Run: SQLERY_DATABASE_URL=<pg_url> alembic upgrade head
  3. Restart workers and daemons.

Expected duration as a function of table size:
  The INSERT ... SELECT copies every row. Budget ~1 min per 1M rows on modern
  hardware with a local PG instance; network-attached storage may be 3-5x slower.
  For tables > 10M rows consider running the SQL in upgrade() manually during a
  maintenance window, then: alembic stamp 20260612_0016 (NOT --fake-initial).

Escape hatch for huge tables (D3):
  Run the SQL statements in upgrade() manually during a maintenance window, then:
  alembic stamp 20260612_0016

Rollback:
  The legacy table (sqlery_queued_job_legacy) is intentionally kept — rollback is
  a rename swap, not a copy. See downgrade(). DROP TABLE sqlery_queued_job_legacy
  is a SEPARATE later migration after soak.

SQLite: this migration is a no-op. The vendor guard returns immediately.

Index byte-identity invariant (D7):
  sqlery_job_pending_idx is recreated with the same definition as Django migration
  0028. If either definition changes, change both.

SHARED-ID-SEQUENCE DECISION (2026-06-11):
  Before S1, we create sqlery_job_id_seq (IF NOT EXISTS) and set the id column
  DEFAULT to nextval('sqlery_job_id_seq') on the EXISTING plain table so that
  S2 (LIKE ... INCLUDING DEFAULTS) copies the shared-sequence default to the new
  partitioned table. This mirrors Django 0029 + 0030. Adding GENERATED BY DEFAULT
  AS IDENTITY would create a second per-table identity sequence — do NOT do that.

Revision ID: 20260612_0016
Revises: 20260608_0015
Create Date: 2026-06-12
"""

from datetime import datetime, timedelta, timezone

import sqlalchemy as sa
from alembic import op
from sqlalchemy import text

revision = '20260612_0016'
down_revision = '20260608_0015'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Idempotent partition cutover for sqlery_queued_job on PostgreSQL.

    No-op on SQLite (D6 — vendor guard returns immediately).

    Steps (mirrors Django migration 0030 S0-S9):
      S0  Drop FK constraints referencing sqlery_queued_job
      S1  Idempotent rename sqlery_queued_job -> sqlery_queued_job_legacy
      Seq CREATE SEQUENCE IF NOT EXISTS sqlery_job_id_seq + SET DEFAULT
      S2  CREATE TABLE sqlery_queued_job LIKE legacy INCLUDING DEFAULTS PARTITION BY RANGE
      S3  ADD PRIMARY KEY (created_at, id) — catalog-guarded
      S3b DROP CONSTRAINT IF EXISTS sqlery_queued_job_job_name_key
      S4  (REMOVED — shared-sequence default already copied by S2 LIKE INCLUDING DEFAULTS)
      S5  CREATE DEFAULT partition
      S6  Recreate sqlery_job_pending_idx (byte-identical to Django 0028 — D7)
      S7  Historical + lookahead daily partitions before bulk copy
      S8  INSERT INTO sqlery_queued_job SELECT * FROM legacy ON CONFLICT DO NOTHING
      S9  Seed sqlery_job_id_seq past max(id)
    """
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        # D6 — no-op on SQLite and any other non-PG vendor
        return

    # S0 — Drop FK constraints referencing sqlery_queued_job BEFORE renaming.
    # Constraint names are auto-generated; discover from information_schema.
    # Idempotent: DROP CONSTRAINT IF EXISTS is a no-op if already gone.
    bind.execute(text("""
        DO $$
        DECLARE
            r RECORD;
        BEGIN
            FOR r IN
                SELECT tc.table_name, tc.constraint_name
                FROM information_schema.table_constraints tc
                JOIN information_schema.referential_constraints rc
                  ON tc.constraint_name = rc.constraint_name
                JOIN information_schema.constraint_column_usage ccu
                  ON rc.unique_constraint_name = ccu.constraint_name
                WHERE ccu.table_name = 'sqlery_queued_job'
                  AND tc.constraint_type = 'FOREIGN KEY'
            LOOP
                EXECUTE format(
                    'ALTER TABLE %I DROP CONSTRAINT IF EXISTS %I',
                    r.table_name, r.constraint_name
                );
            END LOOP;
        END $$;
    """))

    # S1 — Idempotent rename: sqlery_queued_job -> sqlery_queued_job_legacy.
    # Guard: only renames if legacy does not yet exist and source does exist.
    bind.execute(text("""
        DO $$ BEGIN
            IF to_regclass('public.sqlery_queued_job_legacy') IS NULL
               AND to_regclass('public.sqlery_queued_job') IS NOT NULL THEN
                ALTER TABLE sqlery_queued_job RENAME TO sqlery_queued_job_legacy;
            END IF;
        END $$;
    """))

    # Seq — Create shared sequence (IF NOT EXISTS) and set id column DEFAULT
    # on the legacy table so that S2 LIKE INCLUDING DEFAULTS copies it.
    # On a fresh standalone install the legacy table may not exist (no cutover
    # needed; database.py already created the partitioned table).  Check first.
    legacy_exists = bind.execute(text(
        "SELECT to_regclass('public.sqlery_queued_job_legacy')"
    )).scalar()

    if legacy_exists is None:
        # No legacy table — check if sqlery_queued_job already exists as partitioned.
        existing_kind = bind.execute(text(
            "SELECT relkind FROM pg_class WHERE relname = 'sqlery_queued_job'"
        )).scalar()
        if existing_kind == "p":
            # Already partitioned (e.g. database.py was used for fresh install).
            # Only ensure sequence + seeding are done; skip rename/copy steps.
            bind.execute(text("CREATE SEQUENCE IF NOT EXISTS sqlery_job_id_seq"))
            bind.execute(text(
                "SELECT setval('sqlery_job_id_seq',"
                " GREATEST((SELECT COALESCE(MAX(id), 0) FROM sqlery_queued_job), 1),"
                " (SELECT COUNT(*) > 0 FROM sqlery_queued_job))"
            ))
            return
        # Neither legacy nor plain table exists — nothing to migrate; bail out.
        # (This should not happen on a properly initialized standalone DB.)
        return

    bind.execute(text("CREATE SEQUENCE IF NOT EXISTS sqlery_job_id_seq"))
    # Set DEFAULT on legacy table's id column so LIKE INCLUDING DEFAULTS copies it.
    # Idempotent: ALTER COLUMN SET DEFAULT is always safe to re-run.
    bind.execute(text(
        "ALTER TABLE sqlery_queued_job_legacy"
        " ALTER COLUMN id SET DEFAULT nextval('sqlery_job_id_seq');"
    ))

    # S2 — Create partitioned table LIKE legacy (copies id DEFAULT nextval seq).
    # INCLUDING DEFAULTS copies DEFAULT nextval('sqlery_job_id_seq') from legacy.
    # NOT INCLUDING IDENTITY so we do not create a second per-table identity seq.
    bind.execute(text("""
        CREATE TABLE IF NOT EXISTS sqlery_queued_job (
            LIKE sqlery_queued_job_legacy
            INCLUDING DEFAULTS INCLUDING STORAGE
        ) PARTITION BY RANGE (created_at);
    """))

    # S3 — Add composite primary key (catalog-guarded for idempotency).
    pk_count = bind.execute(text("""
        SELECT COUNT(*) FROM pg_constraint
        WHERE conrelid = 'sqlery_queued_job'::regclass AND contype = 'p'
    """)).scalar()
    if not pk_count:
        bind.execute(text(
            "ALTER TABLE sqlery_queued_job ADD PRIMARY KEY (created_at, id);"
        ))

    # S3b — Drop job_name unique constraint if it was carried over.
    # PG partitioned tables cannot have a global single-column unique constraint.
    # LIKE INCLUDING DEFAULTS does NOT copy constraints, so this is a defensive guard.
    bind.execute(text("""
        ALTER TABLE sqlery_queued_job
            DROP CONSTRAINT IF EXISTS sqlery_queued_job_job_name_key;
    """))

    # S4 — (REMOVED — SHARED-ID-SEQUENCE DECISION 2026-06-11)
    # The id column already has DEFAULT nextval('sqlery_job_id_seq') copied from
    # the legacy table by LIKE INCLUDING DEFAULTS in S2.  Do NOT add GENERATED BY
    # DEFAULT AS IDENTITY — that would create a second per-table identity sequence.

    # S5 — Default partition (catch-all).
    bind.execute(text("""
        CREATE TABLE IF NOT EXISTS sqlery_queued_job_default
            PARTITION OF sqlery_queued_job DEFAULT;
    """))

    # S6 — Partial pending index (byte-identical to Django 0028 — D7 invariant).
    # After S1 renames the table the index moves to sqlery_queued_job_legacy.
    # IF NOT EXISTS would find the name there and skip creation on the partitioned
    # table.  Drop from legacy first, then create fresh on the partitioned parent.
    #
    # Old (wrong — IF NOT EXISTS finds the name on legacy and silently skips):
    # CREATE INDEX IF NOT EXISTS sqlery_job_pending_idx ...
    bind.execute(text("DROP INDEX IF EXISTS sqlery_job_pending_idx;"))
    # WR-02: add IF NOT EXISTS so a partial-failure re-run (crash between S6 and S9)
    # does not hit "already exists" on the partitioned table. On the FIRST run the
    # preceding DROP IF EXISTS removed the index from the legacy table, so IF NOT EXISTS
    # correctly creates it fresh on the partitioned parent; on a re-run the index is
    # already on the partitioned table and IF NOT EXISTS skips creation.
    # Old (no guard — re-run fails with "already exists"):
    # CREATE INDEX sqlery_job_pending_idx ...
    bind.execute(text("""
        CREATE INDEX IF NOT EXISTS sqlery_job_pending_idx
            ON sqlery_queued_job (queue_name, priority DESC, created_at)
            WHERE status = 'queued';
    """))

    # S7 — Historical daily partitions BEFORE the bulk copy (prevents DEFAULT trap).
    # Determine the date range of existing rows in the legacy table.
    min_ts, max_ts = bind.execute(text(
        "SELECT MIN(created_at), MAX(created_at) FROM sqlery_queued_job_legacy"
    )).fetchone()

    PREMAKE = 7
    now_utc = datetime.now(timezone.utc)

    if min_ts is not None:
        if min_ts.tzinfo is None:
            min_ts = min_ts.replace(tzinfo=timezone.utc)
        start = min_ts.replace(hour=0, minute=0, second=0, microsecond=0)
    else:
        start = now_utc.replace(hour=0, minute=0, second=0, microsecond=0)

    end = now_utc.replace(hour=0, minute=0, second=0, microsecond=0) + timedelta(
        days=PREMAKE + 1
    )

    current = start
    while current < end:
        next_day = current + timedelta(days=1)
        partition_name = "sqlery_queued_job_" + current.strftime("%Y%m%d")
        from_ts = current.strftime("%Y-%m-%d")
        to_ts = next_day.strftime("%Y-%m-%d")
        # Partition date literals are derived from strftime (digits/dashes only).
        # DDL FOR VALUES FROM/TO cannot use parameterized binds in PG.
        bind.execute(text(
            f"CREATE TABLE IF NOT EXISTS {partition_name}"
            " PARTITION OF sqlery_queued_job"
            f" FOR VALUES FROM ('{from_ts}') TO ('{to_ts}');"
        ))
        current = next_day

    # S8 — Bulk copy (ON CONFLICT DO NOTHING makes it idempotent on re-run).
    bind.execute(text("""
        INSERT INTO sqlery_queued_job
            SELECT * FROM sqlery_queued_job_legacy
            ON CONFLICT DO NOTHING;
    """))

    # S9 — Seed shared sequence past max id so new inserts continue from max+1.
    # setval(name, N, true)  -> nextval() returns N+1 (last value WAS consumed)
    # setval(name, 1, false) -> nextval() returns 1   (empty table)
    bind.execute(text(
        "SELECT setval('sqlery_job_id_seq',"
        " GREATEST((SELECT COALESCE(MAX(id), 0) FROM sqlery_queued_job), 1),"
        " (SELECT COUNT(*) > 0 FROM sqlery_queued_job))"
    ))


def downgrade() -> None:
    """Rollback: restore unpartitioned sqlery_queued_job from the live partitioned table.

    Creates an unpartitioned copy (LIKE sqlery_queued_job INCLUDING DEFAULTS),
    copies all rows back, then renames the partitioned table out of the way and
    promotes the unpartitioned copy to sqlery_queued_job. The unpartitioned table
    inherits DEFAULT nextval('sqlery_job_id_seq') via INCLUDING DEFAULTS.
    The legacy table (sqlery_queued_job_legacy) is NOT dropped — deferred per D3.
    """
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return

    # Step 1 — Create unpartitioned rollback table with composite PK.
    # LIKE INCLUDING DEFAULTS copies the shared-sequence default.
    # PK is added explicitly so ON CONFLICT DO NOTHING in step 2 can detect dups.
    bind.execute(text("""
        CREATE TABLE IF NOT EXISTS sqlery_queued_job_unpartitioned (
            LIKE sqlery_queued_job INCLUDING DEFAULTS INCLUDING STORAGE
        );
    """))
    rb_pk_count = bind.execute(text("""
        SELECT COUNT(*) FROM pg_constraint
        WHERE conrelid = 'sqlery_queued_job_unpartitioned'::regclass
          AND contype = 'p'
    """)).scalar()
    if not rb_pk_count:
        bind.execute(text(
            "ALTER TABLE sqlery_queued_job_unpartitioned"
            " ADD PRIMARY KEY (created_at, id);"
        ))

    # Step 2 — Copy rows back from the partitioned table.
    bind.execute(text("""
        INSERT INTO sqlery_queued_job_unpartitioned
            SELECT * FROM sqlery_queued_job
            ON CONFLICT DO NOTHING;
    """))

    # Step 3 — Rename the partitioned table out of the way (dual-guard for re-run safety).
    bind.execute(text("""
        DO $$ BEGIN
            IF to_regclass('public.sqlery_queued_job') IS NOT NULL
               AND to_regclass('public.sqlery_queued_job_partitioned_bak') IS NULL THEN
                ALTER TABLE sqlery_queued_job RENAME TO sqlery_queued_job_partitioned_bak;
            END IF;
        END $$;
    """))

    # Step 4 — Promote unpartitioned copy to sqlery_queued_job.
    # WR-01: wrap in an existence guard (mirrors Step 3's dual-guard) so a re-run
    # after a crash between this rename and recording the new head does not fail
    # because sqlery_queued_job_unpartitioned was already renamed away.
    # Old (bare rename — not idempotent):
    # bind.execute(text(
    #     "ALTER TABLE sqlery_queued_job_unpartitioned RENAME TO sqlery_queued_job;"
    # ))
    bind.execute(text("""
        DO $$ BEGIN
            IF to_regclass('public.sqlery_queued_job_unpartitioned') IS NOT NULL
               AND to_regclass('public.sqlery_queued_job') IS NULL THEN
                ALTER TABLE sqlery_queued_job_unpartitioned RENAME TO sqlery_queued_job;
            END IF;
        END $$;
    """))
