# Generated by Django 5.2.7 on 2025-10-09 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name for this task', max_length=255, unique=True)),
                ('task_path', models.CharField(help_text="Python path to callable (e.g., 'myapp.tasks.my_function')", max_length=500)),
                ('cron_expression', models.CharField(help_text="Cron expression (e.g., '0 2 * * *' for 2 AM daily)", max_length=100)),
                ('queue_name', models.CharField(default='default', help_text='Queue name for job routing', max_length=50)),
                ('priority', models.IntegerField(default=0, help_text='Priority for enqueued jobs (higher = sooner)')),
                ('enabled', models.BooleanField(default=True, help_text='Whether this task should run')),
                ('last_run_at', models.DateTimeField(blank=True, help_text='Last successful execution time (UTC)', null=True)),
                ('next_run_at', models.DateTimeField(help_text='Next scheduled execution time (UTC)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sqlery_scheduled_task',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['enabled', 'next_run_at'], name='django_sql__enabled_cb9f86_idx')],
            },
        ),
        migrations.CreateModel(
            name='QueuedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_path', models.CharField(help_text="Python path to callable (e.g., 'myapp.tasks.my_function')", max_length=500)),
                ('kwargs', models.JSONField(blank=True, default=dict, help_text='Keyword arguments to pass to task function')),
                ('queue_name', models.CharField(db_index=True, default='default', help_text='Queue name for job routing', max_length=50)),
                ('priority', models.IntegerField(db_index=True, default=0, help_text='Priority (higher = sooner)')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='queued', max_length=10)),
                ('retry_count', models.IntegerField(default=0, help_text='Current retry attempt number (0 = first attempt)')),
                ('max_retries', models.IntegerField(default=0, help_text='Maximum number of retry attempts (0 = no retries)')),
                ('retry_backoff', models.FloatField(default=1.0, help_text='Exponential backoff multiplier (seconds between retries)')),
                ('allow_parallel', models.BooleanField(default=False, help_text='Allow multiple jobs from same queue to run in parallel (default: false for safety)')),
                ('timeout_seconds', models.IntegerField(blank=True, help_text='Maximum execution time in seconds (None = no timeout)', null=True)),
                ('worker_pid', models.IntegerField(blank=True, help_text='Process ID of worker executing this job (for external kill on timeout)', null=True)),
                ('runs', models.JSONField(blank=True, default=list, help_text='History of all execution attempts')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When job was enqueued')),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, help_text='When job should run (NULL = run immediately)', null=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='When execution began', null=True)),
                ('finished_at', models.DateTimeField(blank=True, help_text='When execution completed', null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('output', models.TextField(blank=True, help_text='Task return value or stdout')),
                ('error', models.TextField(blank=True, help_text='Error message if failed')),
                ('traceback', models.TextField(blank=True, help_text='Full traceback if failed')),
                ('scheduled_task', models.ForeignKey(blank=True, help_text='The scheduled task that created this job (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='sqlery.scheduledtask')),
            ],
            options={
                'db_table': 'sqlery_queued_job',
                'ordering': ['-priority', 'created_at'],
                'indexes': [models.Index(fields=['queue_name', 'status', '-priority', 'created_at'], name='django_sql__queue_n_d31814_idx'), models.Index(fields=['task_path', 'status'], name='django_sql__task_pa_0366de_idx')],
            },
        ),
    ]
