# Generated by Django 5.2.7 on 2025-10-16

import uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_id', models.CharField(db_index=True, help_text='Hostname or container ID where worker is running', max_length=255)),
                ('pid', models.IntegerField(help_text='Process ID of worker')),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('busy', 'Busy'), ('dead', 'Dead')], db_index=True, default='idle', max_length=10)),
                ('queues', models.JSONField(default=list, help_text='List of queue names this worker handles')),
                ('last_heartbeat', models.DateTimeField(auto_now=True, db_index=True, help_text='Last time worker sent heartbeat')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('jobs_processed', models.IntegerField(default=0, help_text='Total number of jobs processed by this worker')),
                ('current_job', models.ForeignKey(blank=True, help_text='Job currently being processed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_worker', to='sqlery.queuedjob')),
            ],
            options={
                'db_table': 'sqlery_worker',
                'ordering': ['-started_at'],
                'indexes': [
                    models.Index(fields=['node_id', 'status'], name='django_sql__node_id_status_idx'),
                    models.Index(fields=['status', 'last_heartbeat'], name='django_sql__status_heartbeat_idx'),
                ],
            },
        ),
        migrations.AddField(
            model_name='queuedjob',
            name='worker',
            field=models.ForeignKey(blank=True, help_text='Worker currently processing this job', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to='sqlery.worker'),
        ),
    ]
