# Generated by Django 5.2.7 on 2025-10-16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlery', '0002_worker_multi_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registry_type', models.CharField(choices=[('started', 'Started'), ('finished', 'Finished'), ('failed', 'Failed'), ('scheduled', 'Scheduled'), ('deferred', 'Deferred'), ('canceled', 'Canceled')], db_index=True, help_text='Registry type', max_length=20)),
                ('entered_at', models.DateTimeField(auto_now_add=True, help_text='When job entered this registry')),
                ('exited_at', models.DateTimeField(blank=True, help_text='When job exited this registry (NULL = still active)', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (error info, duration, etc.)')),
                ('job', models.ForeignKey(help_text='Job being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='registry_entries', to='sqlery.queuedjob')),
            ],
            options={
                'verbose_name_plural': 'Job registries',
                'db_table': 'sqlery_registry',
                'ordering': ['-entered_at'],
                'indexes': [
                    models.Index(fields=['registry_type', 'entered_at'], name='django_sql__registr_type_entered_idx'),
                    models.Index(fields=['job', 'registry_type'], name='django_sql__job_registry_idx'),
                    models.Index(fields=['registry_type', 'exited_at'], name='django_sql__registr_type_exited_idx'),
                ],
            },
        ),
    ]
