# Generated by Django 5.2.8 on 2025-11-25 19:16

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlery', '0011_add_version_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queuedjob',
            options={'ordering': ['-priority', 'created_at'], 'verbose_name': 'Job', 'verbose_name_plural': 'Jobs'},
        ),
        migrations.AlterModelOptions(
            name='scheduledtask',
            options={'ordering': ['name'], 'verbose_name': 'Task', 'verbose_name_plural': 'SQLery Dashboard'},
        ),
        migrations.RemoveIndex(
            model_name='queuedjob',
            name='idx_queuedjob_rate_limit',
        ),
        migrations.RemoveIndex(
            model_name='queuedjob',
            name='idx_queuedjob_tags',
        ),
        migrations.RenameIndex(
            model_name='jobregistry',
            new_name='sqlery_regi_registr_a0be0b_idx',
            old_name='django_sql__registr_type_entered_idx',
        ),
        migrations.RenameIndex(
            model_name='jobregistry',
            new_name='sqlery_regi_job_id_404819_idx',
            old_name='django_sql__job_registry_idx',
        ),
        migrations.RenameIndex(
            model_name='jobregistry',
            new_name='sqlery_regi_registr_f8079f_idx',
            old_name='django_sql__registr_type_exited_idx',
        ),
        migrations.RenameIndex(
            model_name='queuedjob',
            new_name='sqlery_queu_queue_n_5c87d6_idx',
            old_name='django_sql__queue_n_d31814_idx',
        ),
        migrations.RenameIndex(
            model_name='queuedjob',
            new_name='sqlery_queu_task_pa_cf2fe6_idx',
            old_name='django_sql__task_pa_0366de_idx',
        ),
        migrations.RenameIndex(
            model_name='scheduledtask',
            new_name='sqlery_sche_enabled_e41524_idx',
            old_name='django_sql__enabled_cb9f86_idx',
        ),
        migrations.RenameIndex(
            model_name='worker',
            new_name='sqlery_work_node_id_e131d6_idx',
            old_name='django_sql__node_id_status_idx',
        ),
        migrations.RenameIndex(
            model_name='worker',
            new_name='sqlery_work_status_cc3650_idx',
            old_name='django_sql__status_heartbeat_idx',
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='next_run_at',
            field=models.DateTimeField(blank=True, help_text='Next scheduled execution time (UTC)', null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='id',
            field=models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False),
        ),
    ]
