# Generated by Django 5.2.8 on 2025-11-26 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlery', '0012_alter_queuedjob_options_alter_scheduledtask_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='worker',
            constraint=models.UniqueConstraint(fields=('node_id', 'pid'), name='unique_worker_per_node_pid'),
        ),
    ]
