# Generated by Django 5.2.12 on 2026-03-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlery', '0015_queuedjob_meta_job_name_retry_intervals'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='scheduledtask',
            new_name='sqlery_sche_schedul_d053ca_idx',
            old_name='sqlery_sche_schedul_idx',
        ),
        migrations.AddField(
            model_name='worker',
            name='paused_until',
            field=models.DateTimeField(blank=True, help_text='If set, worker will not claim jobs until this time', null=True),
        ),
    ]
