# Generated by Django 5.2.12 on 2026-03-15 23:40

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlery', '0021_queuedjob_parent_job_id_archived_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobregistry',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Additional metadata (error info, duration, etc.)'),
        ),
        migrations.AlterField(
            model_name='queuedjob',
            name='dependencies',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='List of job IDs that must complete successfully before this job can run'),
        ),
        migrations.AlterField(
            model_name='queuedjob',
            name='kwargs',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Keyword arguments to pass to task function'),
        ),
        migrations.AlterField(
            model_name='queuedjob',
            name='meta',
            field=models.JSONField(blank=True, default=None, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Free-form metadata dict for task functions (persisted to DB)', null=True),
        ),
        migrations.AlterField(
            model_name='queuedjob',
            name='on_failure_path',
            field=models.CharField(blank=True, help_text='Import path for failure callback', max_length=500),
        ),
        migrations.AlterField(
            model_name='queuedjob',
            name='on_success_path',
            field=models.CharField(blank=True, help_text='Import path for success callback', max_length=500),
        ),
        migrations.AlterField(
            model_name='queuedjob',
            name='retry_intervals',
            field=models.JSONField(blank=True, default=None, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Fixed retry delay list in seconds [5, 10, 60]. Overrides exponential backoff when set.', null=True),
        ),
        migrations.AlterField(
            model_name='queuedjob',
            name='runs',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='History of all execution attempts'),
        ),
        migrations.AlterField(
            model_name='queuedjob',
            name='tags',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text="Tags for concurrency limiting (e.g., ['acme-api', 'rate-limited'])"),
        ),
        migrations.AlterField(
            model_name='queuedjob',
            name='webhook_events',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text="Events that trigger webhook: ['success', 'failure'] or subset"),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='task_kwargs',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Keyword arguments to pass to the task callable on each run'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='queues',
            field=models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='List of queue names this worker handles'),
        ),
    ]
