# Generated by Django 5.2.14 on 2026-05-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlery', '0026_add_shutting_down_status'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='daemoncommand',
            new_name='sqlery_daem_status_8c3bf3_idx',
            old_name='sqlery_daem_status_created_idx',
        ),
        migrations.AlterField(
            model_name='daemoncommand',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='queuedjob',
            name='failure_ttl',
            field=models.IntegerField(blank=True, help_text='Seconds to keep failed job data (-1 = forever, None = use global)', null=True),
        ),
    ]
