# Generated by Django 6.0.5 on 2026-06-14 18:09

import sqlery.django_sqlery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sqlery", "0031_secondary_indexes"),
    ]

    # State-only: the physical column is already correct (Postgres BIGINT with the
    # nextval('sqlery_job_id_seq') default from migrations 0029-0030; SQLite keeps
    # its existing column). Running a real AlterField would force a SQLite table
    # rebuild that trips the demoted sqlery_worker -> sqlery_queued_job FK
    # ("foreign key mismatch"). So we update Django's migration state only —
    # which is all that's needed to clear fields.E100 — and emit no DDL.
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name="queuedjob",
                    name="id",
                    field=models.BigIntegerField(
                        default=sqlery.django_sqlery.models._generate_job_id,
                        editable=False,
                    ),
                ),
            ],
        ),
    ]
